# -*- coding: utf-8 -*-
"""CodeAlpha_IrisFlowerClassification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GmjDi51f9fi8x-dQ8o0kSukFeubJWOwJ

importing libraries :
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

"""loading dataset :"""

df= pd.read_csv("Iris.csv")
df.head()

"""checking basic information :"""

df.info()

"""preprocess data"""

df = df.drop(columns=['Id'])
le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])

"""split features, label and splitting them into training and testing sets:"""

x= df.drop('Species', axis=1)
y= df['Species']
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

"""train model:"""

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(x_train,y_train)

"""evaluate model:"""

y_pred = model.predict(x_test)
print("\n accuracy: ", accuracy_score(y_test,y_pred))
print("\n confusion matrix: \n", confusion_matrix(y_test,y_pred))
print("\n classification report: \n", classification_report(y_test,y_pred,))

"""predict with value:"""

sample=[[5.8, 2.7, 5.1, 1.9]]
prediction= model.predict(sample)
print("predicted species:", le.inverse_transform(prediction))